set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS33} [get_ports en]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports clk]
set_property -dict {PACKAGE_PIN R1 IOSTANDARD LVCMOS33} [get_ports clr]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS33} [get_ports d]
set_property -dict {PACKAGE_PIN A21 IOSTANDARD LVCMOS33} [get_ports q]